# Generated by Django 5.1.4 on 2024-12-20 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0003_application'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Заявку', 'verbose_name_plural': 'заявки на поставку'},
        ),
    ]
